sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "12"

before_script:
  - redis-server --daemonize yes

addons:
  apt:
    packages:
      - redis-server

after_success:
  - yarn run coveralls
