sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "12"

before_script:
  - redis-server --version
  - redis-server --daemonize yes

after_success:
  - yarn run coveralls
